"""Minimal public exports for the current `G1` implementation step."""

from .config import ProjectConfig
from .ontology import (
    GOTerm,
    GeneOntology,
    ancestors_of,
    canonicalize_go_id,
    filter_terms_to_subontology,
    parents_of,
    propagate_scores,
    propagate_terms,
    read_go_obo,
    subontology_terms,
    terms_of_interest,
)
from .types import (
    AspectCode,
    BenchmarkBundle,
    CurvePoint,
    EvaluationResult,
    GoId,
    ProteinId,
    ProteinTaxonRecord,
    ProteinTermRecord,
    SequenceRecord,
    SourceSnapshot,
    Subontology,
    TaxonId,
    TaxonRecord,
    ValidationMismatch,
    ValidationReport,
)

__all__ = [
    "AspectCode",
    "BenchmarkBundle",
    "CurvePoint",
    "EvaluationResult",
    "GOTerm",
    "GeneOntology",
    "GoId",
    "ProjectConfig",
    "ProteinId",
    "ProteinTaxonRecord",
    "ProteinTermRecord",
    "SequenceRecord",
    "SourceSnapshot",
    "Subontology",
    "TaxonId",
    "TaxonRecord",
    "ValidationMismatch",
    "ValidationReport",
    "ancestors_of",
    "canonicalize_go_id",
    "filter_terms_to_subontology",
    "parents_of",
    "propagate_scores",
    "propagate_terms",
    "read_go_obo",
    "subontology_terms",
    "terms_of_interest",
]
